### PR TITLE
Bump zoonavigator to v1.1.1

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by Lowess** [comment]
Hi @simPod do you mind bumping up the chart version as well so that I can release it right away ? It should be 0.1.2

Thanks for your contribution

**Comment by simPod** [comment]
Done, shouldn't I bump also appVersion?

**Comment by Lowess** [comment]
I think we could as well but the chart does not make use of it. Do you mind bumping it as well ?

**Comment by simPod** [comment]
What about now?

**Pull request merged**
